# Generated by Django 5.1.2 on 2026-01-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_delete_samplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他')], default=19, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(),
        ),
    ]
