# Generated by Django 5.1.2 on 2026-01-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_comment_book_created_book_created_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category2',
            field=models.CharField(choices=[('1', '下版作業中'), ('2', 'PDF待ち'), ('3', 'PDF作成済み'), ('4', '先方確認中'), ('5', '三協美術に依頼')], default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('1', '下版予定'), ('2', '下版済み'), ('3', '作業中'), ('4', '最終確認中'), ('5', '作業完了')], max_length=100),
        ),
    ]
