# Generated by Django 5.1.2 on 2026-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_category2_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('1', '下版予定'), ('2', '下版済み'), ('3', '作業中'), ('4', '最終確認中'), ('5', '作業完了')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category2',
            field=models.CharField(blank=True, choices=[('1', '下版作業中'), ('2', 'PDF待ち'), ('3', 'PDF作成済み'), ('4', '先方確認中'), ('5', '三協美術に依頼')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
