# Generated by Django 5.1.2 on 2026-01-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_category_alter_book_category2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pecenrt',
            new_name='percent',
        ),
    ]
