# Generated by Django 5.1.2 on 2026-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_rename_pecenrt_book_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
