# Generated by Django 5.1.2 on 2026-01-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='due_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
